nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- About:
  - License: license.md
  - Release Notes: https://github.com/jhunufernandes/python-docs-generator/releases
  - Issue Tracker: https://github.com/jhunufernandes/python-docs-generator/issues
- API Reference: []
repo_name: python-docs-generator
repo_url: https://github.com/jhunufernandes/python-docs-generator/
site_author: Jhunu Fernandes
site_description: A core package for generating Python Docs using MkDocs.
site_name: python-docs-generator
site_url: https://jhunufernandes.github.io/python-docs-generator/
theme: readthedocs
