name: docs
on:
  push:
    branches:
      - development
jobs:
  install-deps:
    uses: jhunufernandes/python-github-actions/.github/workflows/deps.yml@main
    with:
      pip_args: stage
  deploy-docs:
    needs:
      - install-deps
    uses: jhunufernandes/python-github-actions/.github/workflows/docs.yml@main
