name: docs
on:
  push:
    branches:
      - development
jobs:
  install-deps:
    uses: jhunufernandes/python-github-actions/.github/workflows/deps.yml@main
    with:
      pip_args: stage
  deploy-docs:
    needs:
      - install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          unzip venv.zip
      - run: |
          .venv/bin/python -m mkdocs gh-deploy -f docs/mkdocs.yml --force
